# Generated by Django 4.1.3 on 2022-12-07 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('cod_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=35)),
                ('siglas', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosTicket',
            fields=[
                ('estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_estado', models.TextField(blank=True, max_length=120)),
                ('comment_visible', models.BooleanField(default=False)),
                ('fecha_estado', models.DateField(auto_now_add=True)),
                ('hora_estado', models.TimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadosticket')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('area', models.ManyToManyField(blank=True, to='myapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=120)),
                ('lugar', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('hora_solicitud', models.TimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateField(auto_now_add=True, null=True)),
                ('hora_cierre', models.TimeField(auto_now_add=True, null=True)),
                ('registro', models.ManyToManyField(blank=True, to='myapp.registro')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='myapp.ticket'),
        ),
    ]
