# Generated by Django 4.1.3 on 2023-09-13 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('cod_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=35)),
                ('siglas', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('HW', 'HARDWARE'), ('SF', 'SOFTWARE'), ('MV', 'MOVILIARIO'), ('SC', 'SIN CLASIFICACION')], default='SC', max_length=2)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosTicket',
            fields=[
                ('estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_estado', models.TextField(blank=True, max_length=120)),
                ('comment_visible', models.BooleanField(default=False)),
                ('fecha_estado', models.DateField(auto_now_add=True)),
                ('hora_estado', models.TimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estadosticket')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('area', models.ManyToManyField(blank=True, to='myapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=120)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('hora_solicitud', models.TimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('asunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.asunto')),
                ('registro', models.ManyToManyField(blank=True, to='myapp.registro')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.TextField(blank=True, max_length=120)),
                ('diagnostico', models.TextField(blank=True, max_length=120)),
                ('recomendacion', models.TextField(blank=True, max_length=120)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='ticket',
            field=models.ManyToManyField(blank=True, to='myapp.ticket'),
        ),
    ]
